title: Ajay Daniel # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Software Engineer 1
  <br><br>
  <a href="mailto:ajaydaniel001@gmail.com">ajaydaniel001@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/ajaydaniel001/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/ajsad/">Gihub</a> 

